-- 실습 13-1
SELECT * FROM DICT;

SELECT * FROM DICT
WHERE TABLE_NAME LIKE 'USER%';

SELECT * FROM DICT
WHERE TABLE_NAME LIKE 'ALL%';

SELECT * FROM DICT
WHERE TABLE_NAME LIKE 'DBA%';

SELECT * FROM DICT
WHERE TABLE_NAME LIKE 'V$%';

SELECT * FROM USER_OBJECTS
WHERE OBJECT_NAME ='EMP';


-- 실습 13-2
SELECT * FROM DICTIONARY;

-- 실습 13-3
SELECT * --TABLE_NAME
  FROM USER_TABLES;

-- 실습 13-4
SELECT OWNER, TABLE_NAME
  FROM ALL_TABLES;

SELECT OWNER, TABLE_NAME
  FROM ALL_TABLES
 WHERE OWNER ='HR';

-- 실습 13-5
SELECT * FROM DBA_TABLES;

-- 실습 13-6
SELECT * FROM DBA_TABLES;

CONN SYSTEM/MANAGER

-- 실습 13-7
SELECT *
  FROM DBA_USERS
 WHERE USERNAME = 'HR';

-- 실습 13-8
SELECT *
  FROM USER_INDEXES;
  
SELECT *
  FROM USER_INDEXES
 WHERE TABLE_NAME = 'EMP'  ;  

-- 실습 13-9
SELECT *
  FROM USER_IND_COLUMNS
 WHERE TABLE_NAME = 'EMP'  ;

-- 실습 13-10
CREATE INDEX IDX_EMP_DNO
    ON EMP(DNO);

-- 실습 13-11
SELECT * FROM USER_IND_COLUMNS
WHERE INDEX_NAME = 'IDX_EMP_DNO';

-- 실습 13-12
DROP INDEX IDX_EMP_DNO;

-- 실습 13-13
SELECT * FROM USER_IND_COLUMNS
WHERE INDEX_NAME = 'IDX_EMP_DNO';

-- 실습 13-14
SQLPLUS SYSTEM/12345678

GRANT CREATE VIEW TO HR;

-- 실습 13-15
CREATE VIEW VW_EMP20
    AS (SELECT ENO, ENAME, JOB, DNO
          FROM EMP
         WHERE DNO = 20);

SELECT * FROM VW_EMP20;         

-- 실습 13-16
SELECT *
  FROM USER_VIEWS;

-- 실습 13-17
SELECT VIEW_NAME, TEXT_LENGTH, TEXT
  FROM USER_VIEWS;

-- 실습 13-18
SELECT *
  FROM VW_EMP20;

-- 실습 13-19
DROP VIEW VW_EMP20;

-- 실습 13-20
SELECT ROWNUM, 
       E.*
  FROM EMP E;

-- 실습 13-21
SELECT ROWNUM, E.*
  FROM EMP E
ORDER BY SALARY DESC;

-- 실습 13-22
SELECT ROWNUM, E.*
  FROM (SELECT *
          FROM EMP E
        ORDER BY SALARY DESC) E;

SELECT E.*
  FROM EMP E
 WHERE ROWNUM <=10 ;
        

-- 실습 13-23
WITH E AS (SELECT * FROM EMP ORDER BY SALARY DESC)
SELECT ROWNUM, E.*
  FROM E;

-- 실습 13-24
SELECT ROWNUM, E.*
  FROM (SELECT *
          FROM EMP E
        ORDER BY SALARY DESC) E
 WHERE ROWNUM <= 3;

-- 실습 13-25
WITH E AS (SELECT * FROM EMP ORDER BY SALARY DESC)
SELECT ROWNUM, E.*
  FROM E
 WHERE ROWNUM <= 3;

-- 실습 13-26
CREATE TABLE DEPT_SEQUENCE
    AS SELECT *
         FROM DEPT
        WHERE 1 <> 1;

SELECT * FROM DEPT_SEQUENCE;

-- 실습 13-27
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
   INCREMENT BY 10
   START WITH 10
   MAXVALUE 90
   MINVALUE 0
   NOCYCLE
   CACHE 2;

-- 실습 13-28
SELECT *
  FROM USER_SEQUENCES
 WHERE SEQUENCE_NAME = 'SEQ_DEPT_SEQUENCE';

-- 실습 13-29
INSERT INTO DEPT_SEQUENCE (DNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_SEQUENCE ORDER BY DNO;

-- 실습 13-30
SELECT SEQ_DEPT_SEQUENCE.CURRVAL
  FROM DUAL;

-- 실습 13-31
INSERT INTO DEPT_SEQUENCE (DNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_SEQUENCE ORDER BY DNO;

-- 실습 13-32
ALTER SEQUENCE SEQ_DEPT_SEQUENCE
   INCREMENT BY 3
   MAXVALUE 99
   CYCLE;

-- 실습 13-33
SELECT *
  FROM USER_SEQUENCES;

-- 실습 13-34
INSERT INTO DEPT_SEQUENCE (DNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_SEQUENCE ORDER BY DNO;

-- 실습 13-35
INSERT INTO DEPT_SEQUENCE (DNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_SEQUENCE ORDER BY DNO;

-- 실습 13-36
DROP SEQUENCE SEQ_DEPT_SEQUENCE;

SELECT * FROM USER_SEQUENCES;

-- 실습 13-37
SQLPLUS SYSTEM/oracle

GRANT CREATE SYNONYM TO HR;

GRANT CREATE PUBLIC SYNONYM TO HR;

-- 실습 13-38
CREATE SYNONYM E
   FOR EMP;

-- 실습 13-39
SELECT * FROM E;

-- 실습 13-40
DROP SYNONYM E;
