-- 실습 9-1
SELECT SALARY
  FROM EMP
 WHERE ENAME = 'JONES';

-- 실습 9-2
SELECT *
  FROM EMP
 WHERE SALARY > 2975;

-- 실습 9-3
SELECT *
  FROM EMP
 WHERE SALARY > (SELECT SALARY
                FROM EMP
               WHERE ENAME = 'JONES');

-- 실습 9-4
SELECT *
  FROM EMP
 WHERE HIREDATE < (SELECT HIREDATE
                     FROM EMP
                    WHERE ENAME = 'SCOTT');

-- 실습 9-5
SELECT E.ENO, E.ENAME, E.JOB, E.SALARY, D.DNO, D.DNAME, D.LOC
  FROM EMP E, DEPT D
 WHERE E.DNO = D.DNO
   AND E.DNO = 20
   AND E.SALARY > (SELECT AVG(SALARY)
                  FROM EMP);

-- 실습 9-6
SELECT *
  FROM EMP
 WHERE DNO IN (20, 30);

-- 실습 9-7
SELECT *
  FROM EMP
 WHERE SALARY IN (SELECT MAX(SALARY)
                 FROM EMP
               GROUP BY DNO);

-- 실습 9-8
SELECT DNO, MAX(SALARY)
  FROM EMP
GROUP BY DNO;

-- 실습 9-9
SELECT *
  FROM EMP
 WHERE SALARY = ANY (SELECT MAX(SALARY)
                    FROM EMP
                  GROUP BY DNO);

-- 실습 9-10
SELECT *
  FROM EMP
 WHERE SALARY = SOME (SELECT MAX(SALARY)
                     FROM EMP
                   GROUP BY DNO);

SELECT *
  FROM EMP
 WHERE SALARY IN (2850,3000,5000);
 
SELECT *
  FROM EMP
 WHERE SALARY = 2850
    OR SALARY = 3000
    OR SALARY = 5000;


-- 실습 9-11
SELECT *
  FROM EMP
 WHERE SALARY < ANY (SELECT SALARY
                    FROM EMP
                   WHERE DNO = 30)
                  ORDER BY SALARY, ENO;
                  
SELECT *
  FROM EMP
 WHERE SALARY < 1600
UNION
SELECT *
  FROM EMP
 WHERE SALARY < 1250
UNION
 SELECT *
  FROM EMP
 WHERE SALARY < 1250
UNION
SELECT *
  FROM EMP
 WHERE SALARY < 2850
UNION
SELECT *
  FROM EMP
 WHERE SALARY < 1500
UNION
SELECT *
  FROM EMP
 WHERE SALARY < 950;

-- 실습 9-12
SELECT SALARY
  FROM EMP
 WHERE DNO = 30;

-- 실습 9-13
SELECT *
  FROM EMP
 WHERE SALARY > ANY (SELECT SALARY
                    FROM EMP
                   WHERE DNO = 30);
                   
SELECT *
  FROM EMP
 WHERE SALARY > 1600
UNION
SELECT *
  FROM EMP
 WHERE SALARY > 1250
UNION
 SELECT *
  FROM EMP
 WHERE SALARY > 1250
UNION
SELECT *
  FROM EMP
 WHERE SALARY > 2850
UNION
SELECT *
  FROM EMP
 WHERE SALARY > 1500
UNION
SELECT *
  FROM EMP
 WHERE SALARY > 950;                   

-- 실습 9-14
SELECT *
  FROM EMP
 WHERE SALARY < ALL (SELECT SALARY
                    FROM EMP
                   WHERE DNO = 30);
1600
1250
1250
2850
1500
950

-- 실습 9-15
SELECT *
  FROM EMP
 WHERE SALARY > ALL (SELECT SALARY
                    FROM EMP
                   WHERE DNO = 30);
1600
1250
1250
2850
1500
950
SELECT *
  FROM EMP
 WHERE SALARY > 2850;

-- 실습 9-16
SELECT *
  FROM EMP
 WHERE EXISTS (SELECT DNAME
                 FROM DEPT
                WHERE DNO = 10);
ACCOUNTING

SELECT *
  FROM EMP
 WHERE EXISTS (SELECT DNAME
                 FROM DEPT
                WHERE DNO = 50);

-- 실습 9-17
SELECT *
  FROM EMP
 WHERE EXISTS (SELECT DNAME
                 FROM DEPT
                WHERE DNO = 10);

-- 실습 9-18
SELECT *
  FROM EMP
 WHERE (DNO, SALARY) IN (SELECT DNO, MAX(SALARY)
                           FROM EMP
                         GROUP BY DNO);

SELECT *
  FROM EMP
 WHERE DNO IN ( 30, 20, 10)   
   AND SALARY IN ( 2850, 3000, 5000) ;

	

-- 실습 9-19
SELECT E10.ENO, E10.ENAME, E10.DNO, D.DNAME, D.LOC
  FROM (SELECT * FROM EMP WHERE DNO = 10) E10,
       (SELECT * FROM DEPT) D
 WHERE E10.DNO = D.DNO;

-- 실습 9-20
WITH
E10 AS (SELECT * FROM EMP WHERE DNO = 10),
D AS (SELECT * FROM DEPT)
SELECT E10.ENO, E10.ENAME, E10.DNO, D.DNAME, D.LOC
  FROM E10, D
 WHERE E10.DNO = D.DNO;

-- 실습 9-21
SELECT ENO, ENAME, JOB, SALARY,
       (SELECT GRADE 
          FROM SAL
         WHERE E.SALARY BETWEEN LOSAL AND HISAL) AS SALGRADE,
       DNO,
      (SELECT DNAME
         FROM DEPT
        WHERE E.DNO = DEPT.DNO) AS DNAME
FROM EMP E;

SELECT GRADE 
  FROM SAL, EMP E
WHERE E.SALARY BETWEEN LOSAL AND HISAL;

SELECT DNAME
         FROM DEPT, EMP E
        WHERE E.DNO = DEPT.DNO;
        
SELECT ENO, ENAME, JOB, SALARY, DNO
FROM EMP E;        

SELECT ENO, ENAME, JOB, SALARY,
       5,
       DNO,
      'RESEARCH'
 FROM EMP E;      
 
SELECT ENO, ENAME, JOB, SALARY,
       (SELECT GRADE 
          FROM SAL
         WHERE E.SALARY BETWEEN LOSAL AND HISAL) AS SALGRADE,
       DNO,
      (SELECT DNAME
         FROM DEPT
        WHERE E.DNO = DEPT.DNO) AS DNAME
FROM EMP E;
 