-- 실습 8-1
SELECT *
  FROM EMP, DEPT
ORDER BY ENO;

SELECT *
  FROM DEPT;

-- 실습 8-2
SELECT *
  FROM EMP, DEPT
 WHERE EMP.DNO = DEPT.DNO
ORDER BY ENO;

-- 실습 8-3
SELECT *
  FROM EMP E, DEPT D
 WHERE E.DNO = D.DNO
ORDER BY ENO;

-- 실습 8-4
SELECT ENO, ENAME, DNO, DNAME, LOC
  FROM EMP E, DEPT D
 WHERE E.DNO = D.DNO;

-- 실습 8-5
SELECT E.ENO, E.ENAME, D.DNO, D.DNAME, D.LOC
  FROM EMP E, DEPT D
 WHERE E.DNO = D.DNO
ORDER BY D.DNO, E.ENO;

-- 실습 8-6
SELECT E.ENO, E.ENAME, E.SALARY, D.DNO, D.DNAME, D.LOC
  FROM EMP E, DEPT D
 WHERE E.DNO = D.DNO
   AND E.SALARY >= 3000;

-- 실습 8-7
SELECT E.*, S.*
  FROM EMP E, SAL S
WHERE E.SALARY BETWEEN S.LOSAL AND S.HISAL;

SELECT E.*
  FROM EMP E;

SELECT S.*
  FROM SAL S;

--WHERE E.SALARY > S.LOSAL 
--  AND E.SALARY S.LOSAL;
--WHERE E.SALARY BETWEEN 700 AND 1200;
-- 실습 8-8
SELECT E1.ENO, E1.ENAME, E1.MANAGER,
       E2.ENO AS MANAGER_ENO,
       E2.ENAME AS MANAGER_ENAME
  FROM EMP E1, EMP E2
 WHERE E1.MANAGER = E2.ENO;

-- 실습 8-9
SELECT E1.ENO, E1.ENAME, E1.MANAGER,
       E2.ENO AS MANAGER_ENO,
       E2.ENAME AS MANAGER_ENAME
  FROM EMP E1, EMP E2
 WHERE E1.MANAGER = E2.ENO(+)
ORDER BY E1.ENO;

-- 실습 8-10
SELECT E1.ENO, E1.ENAME, E1.MANAGER,
       E2.ENO AS MANAGER_ENO,
       E2.ENAME AS MANAGER_ENAME
  FROM EMP E1, EMP E2
 WHERE E1.MANAGER(+) = E2.ENO
ORDER BY E1.ENO;

-- 실습 8-11
SELECT E.ENO, E.ENAME, E.JOB, E.MANAGER, E.HIREDATE, E.SALARY, E.COMMISSION,
       DNO, D.DNAME, D.LOC
  FROM EMP E NATURAL JOIN DEPT D
ORDER BY DNO, E.ENO;

-- 실습 8-12
SELECT E.ENO, E.ENAME, E.JOB, E.MANAGER, E.HIREDATE, E.SALARY, E.COMMISSION,
       DNO, D.DNAME, D.LOC
  FROM EMP E JOIN DEPT D USING (DNO)
 WHERE SALARY >= 3000
ORDER BY DNO, E.ENO;

-- 실습 8-13
SELECT E.ENO, E.ENAME, E.JOB, E.MANAGER, E.HIREDATE, E.SALARY, E.COMMISSION,
       E.DNO,
       D.DNAME, D.LOC
  FROM EMP E JOIN DEPT D ON (E.DNO = D.DNO)
 WHERE SALARY <= 3000
ORDER BY E.DNO, ENO;

-- 실습 8-14
SELECT E1.ENO, E1.ENAME, E1.MANAGER,
       E2.ENO AS MANAGER_ENO,
       E2.ENAME AS MANAGER_ENAME
  FROM EMP E1 LEFT OUTER JOIN EMP E2 ON (E1.MANAGER = E2.ENO)
ORDER BY E1.ENO;

-- 실습 8-15
SELECT E1.ENO, E1.ENAME, E1.MANAGER,
       E2.ENO AS MANAGER_ENO,
       E2.ENAME AS MANAGER_ENAME
  FROM EMP E1 RIGHT OUTER JOIN EMP E2 ON (E1.MANAGER = E2.ENO)
ORDER BY E1.ENO, MANAGER_ENO;

-- 실습 8-16
SELECT E1.ENO, E1.ENAME, E1.MANAGER,
       E2.ENO AS MANAGER_ENO,
       E2.ENAME AS MANAGER_ENAME
  FROM EMP E1 FULL OUTER JOIN EMP E2 ON (E1.MANAGER = E2.ENO)
ORDER BY E1.ENO;
