SELECT DISTINCT DNO
  FROM EMP;

SELECT DISTINCT DNO 
  FROM DEPT;

--NATURAL JOIN
SELECT *
FROM EMP NATURAL JOIN DEPT;

SELECT DNAME, ENO, ENAME, DNAME
FROM EMP NATURAL JOIN DEPT;

--JOIN ~ USING
SELECT e.empno, e.ename, deptno 
     FROM EMP A JOIN DEPT B USING(DNO);
     

--Equi Join  
SELECT A.DNO, A.DNO EMP_DNO, B.DNO DEPT_DNO, A.*, B.*
  FROM EMP A, DEPT B
  WHERE A.DNO=B.DNO
  ORDER BY A.DNO;

--INNER JOIN
SELECT A.DNO, A.DNO EMP_DNO, B.DNO DEPT_DNO, A.*, B.*
  FROM EMP A INNER JOIN DEPT B
    ON A.DNO=B.DNO;  

--RIGHT OUTER JOIN  
SELECT  A.DNO, A.DNO EMP_DNO, B.DNO DEPT_DNO, A.*, B.*
  FROM EMP A, DEPT B
  WHERE A.DNO(+)=B.DNO
  ORDER BY A.DNO;  

SELECT  A.DNO , A.DNO EMP_DNO, B.DNO DEPT_DNO, A.*, B.*
  FROM EMP A RIGHT OUTER JOIN DEPT B 
  ON A.DNO=B.DNO 
  ORDER BY A.DNO;    
  
SELECT  A.DNO , A.DNO EMP_DNO, B.DNO DEPT_DNO, A.*, B.*
  FROM EMP A, DEPT B
  WHERE A.DNO=B.DNO(+)
  ORDER BY A.DNO;  

--LEFT OUTER JOIN
SELECT A.DNO , A.DNO EMP_DNO, B.DNO DEPT_DNO, A.*, B.*
  FROM EMP A LEFT OUTER JOIN DEPT B 
  ON A.DNO=B.DNO 
  ORDER BY A.DNO;      

--FULL OUTER JOIN  
SELECT  A.DNO, A.DNO EMP_DNO, B.DNO DEPT_DNO, A.*, B.* 
  FROM EMP A FULL OUTER JOIN DEPT B 
  ON A.DNO=B.DNO 
  ORDER BY A.DNO;      



--SELF JOIN  
SELECT * 
FROM EMP;

SELECT E1.ENO AS 사원,
       E1.ENAME AS 사원이름,
       E2.ENO AS 관리자,
       E2.ENAME AS 차상위_관리자
  FROM EMP E1, EMP E2
 WHERE E1.MANAGER = E2.ENO
 ORDER BY E2.MANAGER DESC, E1.MANAGER, E1.ENO;   
 
SELECT  E1.*, E2.*
    FROM EMP E1, EMP E2
 WHERE E1.MANAGER = E2.ENO
 ORDER BY E2.MANAGER DESC, E1.MANAGER, E1.ENO;   
 
SELECT E1.ENO AS 사원 코드,
       E1.ENAME AS 사원이름,
       E2.ENO AS 관리자 코드,
       E2.ENAME AS 관리자 이름
  FROM EMP E1, EMP E2
 WHERE E1.MANAGER = E2.ENO
 ORDER BY E2.MANAGER DESC, E1.MANAGER, E1.ENO;   