-- 실습 7-1
SELECT SUM(SALARY)
  FROM EMP;

-- 실습 7-2
SELECT ENAME, SUM(SALARY)
  FROM EMP;

-- 실습 7-3
SELECT SUM(COMMISSION) --NULL 존재(에러)
  FROM EMP;

-- 실습 7-4
SELECT SUM(DISTINCT SALARY),
       SUM(ALL SALARY),
       SUM(SALARY)
  FROM EMP;

-- 실습 7-5
SELECT COUNT(*)
  FROM EMP;

-- 실습 7-6
SELECT COUNT(*)
  FROM EMP
 WHERE DNO = 30;

-- 실습 7-7
SELECT COUNT(DISTINCT SALARY),
       COUNT(ALL SALARY),
       COUNT(SALARY)
  FROM EMP;

-- 실습 7-8
SELECT COUNT(*)
  FROM EMP;

SELECT *
  FROM EMP;
  
SELECT COUNT(COMMISSION)
  FROM EMP;

-- 실습 7-9
SELECT COUNT(COMMISSION)
  FROM EMP
 WHERE COMMISSION IS NOT NULL;

-- 실습 7-10
SELECT MAX(SALARY)
  FROM EMP
 WHERE DNO = 10;

-- 실습 7-11
SELECT MIN(SALARY)
  FROM EMP
 WHERE DNO = 10;

-- 실습 7-12
SELECT MAX(HIREDATE)
  FROM EMP
 WHERE DNO = 20;

-- 실습 7-13
SELECT MIN(HIREDATE)
  FROM EMP
 WHERE DNO = 20;

-- 실습 7-14
SELECT AVG(SALARY)
  FROM EMP
 WHERE DNO = 30;

-- 실습 7-15
SELECT AVG(DISTINCT SALARY)
  FROM EMP
 WHERE DNO = 30;

-- 실습 7-16
SELECT AVG(SALARY), '10' AS DNO FROM EMP WHERE DNO = 10
UNION ALL
SELECT AVG(SALARY), '20' AS DNO FROM EMP WHERE DNO = 20
UNION ALL
SELECT AVG(SALARY), '30' AS DNO FROM EMP WHERE DNO = 30;

-- 실습 7-17
SELECT DNO, AVG(SALARY)
  FROM EMP
GROUP BY DNO ;

-- 실습 7-18
SELECT DNO, JOB, AVG(SALARY)
  FROM EMP
GROUP BY DNO, JOB
ORDER BY DNO, JOB;

-- 실습 7-19
SELECT ENAME, DNO, AVG(SALARY)
  FROM EMP
GROUP BY DNO;

-- 실습 7-20
SELECT DNO, JOB, AVG(SALARY)
  FROM EMP
GROUP BY DNO, JOB
HAVING AVG(SALARY) >= 2000
ORDER BY DNO DESC, JOB ASC;

-- 실습 7-21
SELECT DNO, JOB, AVG(SALARY)
  FROM EMP
 WHERE AVG(SALARY) >= 2000
GROUP BY DNO, JOB
ORDER BY DNO, JOB;

-- 실습 7-22
SELECT DNO, JOB, AVG(SALARY)
  FROM EMP
GROUP BY DNO, JOB
HAVING AVG(SALARY) >= 2000
ORDER BY DNO, JOB;

-- 실습 7-23
SELECT DNO, JOB, AVG(SALARY)
  FROM EMP
 WHERE SALARY <= 3000
GROUP BY DNO, JOB
HAVING AVG(SALARY) >= 2000
ORDER BY DNO, JOB;

-- 실습 7-24
SELECT DNO, JOB, COUNT(*), MAX(SALARY), SUM(SALARY), AVG(SALARY)
  FROM EMP
GROUP BY DNO, JOB
ORDER BY DNO, JOB;

-- 실습 7-25
SELECT DNO, JOB, 
       COUNT(*), MAX(SALARY), 
       SUM(SALARY), AVG(SALARY)
  FROM EMP
GROUP BY ROLLUP(DNO, JOB);


-- 실습 7-26
SELECT DNO, JOB, COUNT(*), MAX(SALARY), SUM(SALARY), AVG(SALARY)
  FROM EMP
GROUP BY CUBE(DNO, JOB)
ORDER BY DNO, JOB;

-- 실습 7-27
SELECT DNO, JOB, COUNT(*)
  FROM EMP
GROUP BY DNO, ROLLUP(JOB);

-- 실습 7-28
SELECT JOB, DNO,  COUNT(*)
  FROM EMP
GROUP BY JOB, ROLLUP(DNO);

-- 실습 7-29
SELECT DNO, JOB, COUNT(*)
  FROM EMP
GROUP BY GROUPING SETS(DNO, JOB)
ORDER BY DNO, JOB;

-- 실습 7-30
SELECT DNO, JOB, COUNT(*), MAX(SALARY), SUM(SALARY), AVG(SALARY),
       GROUPING(DNO),
       GROUPING(JOB)
  FROM EMP
GROUP BY CUBE(DNO, JOB )
ORDER BY DNO, JOB;

-- 실습 7-31
SELECT DECODE(GROUPING(DNO), 1, 'ALL_DEPT', DNO) AS DNO,
       DECODE(GROUPING(JOB), 1, 'ALL_JOB', JOB) AS JOB,
       COUNT(*), MAX(SALARY), SUM(SALARY), AVG(SALARY)
  FROM EMP
GROUP BY CUBE(DNO, JOB)
ORDER BY DNO, JOB;

-- 실습 7-32
SELECT DNO, JOB, COUNT(*), SUM(SALARY),
       GROUPING(DNO),
       GROUPING(JOB),
       GROUPING_ID(DNO, JOB)
  FROM EMP
GROUP BY CUBE(DNO, JOB)
ORDER BY DNO, JOB;

-- 실습 7-33
SELECT DNO, ENAME
FROM EMP
GROUP BY DNO, ENAME
ORDER BY DNO, ENAME;

-- 실습 7-34
SELECT DNO,
       LISTAGG(ENAME, ', ')
       WITHIN GROUP(ORDER BY SALARY DESC) AS ENAMES
  FROM EMP
GROUP BY DNO;

-- 실습 7-35
SELECT DNO, JOB, MAX(SALARY)
  FROM EMP
GROUP BY DNO, JOB
ORDER BY DNO, JOB;

-- 실습 7-36
SELECT *
  FROM(SELECT DNO, JOB, SALARY
         FROM EMP)
PIVOT(MAX(SALARY)
      FOR DNO IN (10, 20, 30)
      )
ORDER BY JOB;

-- 실습 7-37
SELECT *
  FROM(SELECT JOB, DNO, SALARY
         FROM EMP)
PIVOT(MAX(SALARY)
     FOR JOB IN ('CLERK' AS CLERK,
                 'SALARYESMAN' AS SALARYESMAN,
                 'PRESIDENT' AS PRESIDENT,
                 'MANAGER' AS MANAGER,
                 'ANALYST' AS ANALYST)
     )
ORDER BY DNO;

-- 실습 7-38
SELECT DNO,
       MAX(DECODE(JOB, 'CLERK', SALARY)) AS "CLERK",
       MAX(DECODE(JOB, 'SALARYESMAN', SALARY)) AS "SALARYESMAN",
       MAX(DECODE(JOB, 'PRESIDENT', SALARY)) AS "PRESIDENT",
       MAX(DECODE(JOB, 'MANAGER', SALARY)) AS "MANAGER",
       MAX(DECODE(JOB, 'ANALYST', SALARY)) AS "ANALYST"
  FROM EMP
GROUP BY DNO
ORDER BY DNO;

-- 실습 7-39
SELECT *
  FROM(SELECT DNO,
              MAX(DECODE(JOB, 'CLERK' , SALARY)) AS "CLERK",
              MAX(DECODE(JOB, 'SALARYESMAN' , SALARY)) AS "SALARYESMAN",
              MAX(DECODE(JOB, 'PRESIDENT', SALARY)) AS "PRESIDENT",
              MAX(DECODE(JOB, 'MANAGER' , SALARY)) AS "MANAGER",
              MAX(DECODE(JOB, 'ANALYST' , SALARY)) AS "ANALYST"
         FROM EMP
       GROUP BY DNO
       ORDER BY DNO)
UNPIVOT(
   SALARY FOR JOB IN (CLERK, SALARYESMAN, PRESIDENT, MANAGER,ANALYST))
ORDER BY DNO, JOB;
