SELECT *
  FROM EMP;

SELECT DEPTNO,
       SUM(SAL)
  FROM EMP
  GROUP BY DEPTNO;
 
SELECT DISTINCT DEPTNO
  FROM EMP;
  
SELECT JOB, 
       COUNT(*) AS 직원수,
       SUM(SAL)
  FROM EMP
  GROUP BY JOB
ORDER BY JOB ASC;

SELECT JOB, 
       COUNT(*) AS 직원수,
       SUM(SAL)
  FROM EMP
  GROUP BY JOB
ORDER BY COUNT(*) ASC;

SELECT JOB, 
       COUNT(*) AS 직원수,
       SUM(SAL), ROUND(AVG(SAL),0) AS 평균_급여,
       MIN(SAL), MAX(SAL)
  FROM EMP
  GROUP BY JOB
ORDER BY AVG(SAL) DESC;

SELECT COUNT(*)
  FROM EMP;
  
SELECT DEPTNO,
       SUM(SAL)
  FROM EMP
  GROUP BY DEPTNO; 
  
SELECT '영업',
       SUM(SAL)
  FROM EMP
WHERE DEPTNO = 10
UNION
SELECT '인사',
       SUM(SAL)
  FROM EMP
WHERE DEPTNO = 20
UNION
SELECT '연구',
       SUM(SAL)
  FROM EMP
WHERE DEPTNO = 30;

SELECT SUM(SAL)
  FROM EMP
WHERE DEPTNO IN(10, 20, 30);

SELECT SUM(SAL)
  FROM EMP
WHERE DEPTNO IN(SELECT DISTINCT DEPTNO 
                  FROM EMP
                 WHERE DEPTNO != 10);
                  
SELECT DEPTNO,
       SUM(SAL)
  FROM EMP
 WHERE SAL > 10000
--  WHERE DEPTNO = 10
  GROUP BY DEPTNO
    HAVING SUM(SAL) > 10000
  ORDER BY DEPTNO;      
  

SELECT *
  FROM EMP
 WHERE ROWNUM < 6;
 
== ROLL UP
SELECT *
  FROM EMP ;
  
SELECT DEPTNO, JOB, COUNT(*) AS 직원수,
       SUM(SAL), ROUND(AVG(SAL),0) AS 평균_급여,
       MIN(SAL), MAX(SAL)
  FROM EMP
  GROUP BY DEPTNO, JOB;
--ORDER BY DEPTNO ASC; 

SELECT DEPTNO, JOB, COUNT(*) AS 직원수,
       SUM(SAL), ROUND(AVG(SAL),0) AS 평균_급여,
       MIN(SAL), MAX(SAL)
  FROM EMP
  GROUP BY ROLLUP(DEPTNO, JOB);
--ORDER BY DEPTNO ASC;  

==CUBE 함수
SELECT DEPTNO, JOB, COUNT(*) AS 직원수,
       SUM(SAL), ROUND(AVG(SAL),0) AS 평균_급여,
       MIN(SAL), MAX(SAL)
  FROM EMP
  GROUP BY CUBE(DEPTNO, JOB)
  ORDER BY DEPTNO, JOB;  
  
SELECT DEPTNO, JOB, COUNT(*) AS 직원수,
       SUM(SAL), ROUND(AVG(SAL),0) AS 평균_급여,
       MIN(SAL), MAX(SAL)
  FROM EMP
  GROUP BY DEPTNO, ROLLUP(JOB)
  ORDER BY DEPTNO, JOB;
  
SELECT DEPTNO, JOB, COUNT(*) AS 직원수,
       SUM(SAL), ROUND(AVG(SAL),0) AS 평균_급여,
       MIN(SAL), MAX(SAL)
  FROM EMP
  GROUP BY JOB, ROLLUP(DEPTNO)
  ORDER BY DEPTNO, JOB; 

====GROUPING SETS  
SELECT DEPTNO, JOB, COUNT(*) AS 직원수,
       SUM(SAL), ROUND(AVG(SAL),0) AS 평균_급여,
       MIN(SAL), MAX(SAL)
  FROM EMP
  GROUP BY GROUPING SETS(DEPTNO, JOB)
  ORDER BY DEPTNO, JOB;   

====
SELECT DEPTNO, JOB, COUNT(*) AS 직원수,
       SUM(SAL), ROUND(AVG(SAL),0) AS 평균_급여,
       MIN(SAL), MAX(SAL),
       GROUPING(DEPTNO),
       GROUPING(JOB)
  FROM EMP
  GROUP BY CUBE(DEPTNO, JOB)
  ORDER BY DEPTNO, JOB;   
  
SELECT DEPTNO, JOB, COUNT(*) AS 직원수,
       SUM(SAL), ROUND(AVG(SAL),0) AS 평균_급여,
       MIN(SAL), MAX(SAL),
       GROUPING(DEPTNO),
       GROUPING(JOB),
       GROUPING_ID(DEPTNO, JOB)
  FROM EMP
  GROUP BY CUBE(DEPTNO, JOB)
  ORDER BY DEPTNO, JOB;    
