-- 실습 7-25(ROLL UP 설명)
SELECT DNO, 
       COUNT(*), MAX(SALARY), 
       SUM(SALARY), AVG(SALARY)
  FROM EMP
GROUP BY DNO
ORDER BY DNO;

SELECT JOB, 
       COUNT(*), MAX(SALARY), 
       SUM(SALARY), AVG(SALARY)
  FROM EMP
GROUP BY JOB
ORDER BY JOB;
