-- 실습 10-1
DROP TABLE DEPT_TEMP;

  CREATE TABLE "HR"."DEPT_TEMP" 
   (	"DNO" NUMBER(2,0), 
        "DNAME" VARCHAR2(14 BYTE), 
        "LOC" VARCHAR2(13 BYTE), 
        CONSTRAINT "PK_DEPT_TEMP" PRIMARY KEY ("DNO")
    );
SELECT * FROM DEPT_TEMP;

DROP TABLE DEPT_TEMP;

CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT;

-- 실습 10-2
SELECT * FROM DEPT_TEMP;

-- 실습 10-3
INSERT INTO DEPT_TEMP (DNO, DNAME, LOC)
VALUES (50, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_TEMP;

-- 실습 10-4
INSERT INTO DEPT_TEMP
VALUES (60 , 'NETWORK', 'BUSAN');

SELECT * FROM DEPT_TEMP;

-- 실습 10-5
INSERT INTO DEPT_TEMP (DNO, DNAME, LOC)
VALUES (70 , 'WEB', NULL);

SELECT * FROM DEPT_TEMP;

-- 실습 10-6
INSERT INTO DEPT_TEMP (DNO, DNAME , LOC)
VALUES (80 , 'MOBILE', '');

SELECT * FROM DEPT_TEMP;

-- 실습 10-7
INSERT INTO DEPT_TEMP (DNO, LOC)
VALUES (90 , 'INCHEON');

SELECT * FROM DEPT_TEMP;

-- 실습 10-8
DROP TABLE EMP_TEMP;
CREATE TABLE EMP_TEMP
    AS SELECT *
         FROM EMP
        WHERE 1 <> 1
;--FALSE

SELECT * FROM EMP_TEMP;

-- 실습 10-9
INSERT INTO EMP_TEMP (ENO, ENAME, JOB, MANAGER, HIREDATE, SALARY, COMMISSION, DNO)
VALUES (9999, '홍길동', 'PRESIDENT', NULL, '2001/01/01', 5000, 1000, 10);

SELECT * FROM EMP_TEMP;
ROLLBACK;
-- 실습 10-10
INSERT INTO EMP_TEMP (ENO, ENAME, JOB, MANAGER, HIREDATE, SALARY, COMMISSION, DNO)
VALUES (1111, '성춘향', 'MANAGER', 9999, '2001-01-05', 4000, NULL, 20);

SELECT * FROM EMP_TEMP;

-- 실습 10-11(에러-날자타입)
INSERT INTO EMP_TEMP (ENO, ENAME, JOB, MANAGER , HIREDATE, SALARY , COMMISSION, DNO)
VALUES (2111, '이순신', 'MANAGER', 9999, '07/01/2001', 4000, NULL, 20);

-- 실습 10-12
INSERT INTO EMP_TEMP (ENO, ENAME, JOB, MANAGER, HIREDATE, SALARY, COMMISSION, DNO)
VALUES (2111, '이순신', 'MANAGER', 9999, 
        TO_DATE('07/01/2001', 'DD/MM/YYYY'), 4000, NULL, 20);

     

SELECT * FROM EMP_TEMP;

-- 실습 10-13
INSERT INTO EMP_TEMP (ENO, ENAME, JOB, MANAGER, HIREDATE, SALARY, COMMISSION, DNO)
VALUES (3111, '심청이', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30);

SELECT * FROM EMP_TEMP;

-- 실습 10-14
INSERT INTO EMP_TEMP (ENO, ENAME, JOB, MANAGER, HIREDATE, SALARY, COMMISSION, DNO)
SELECT E.ENO, E.ENAME, E.JOB, E.MANAGER, E.HIREDATE, E.SALARY, E.COMMISSION, E.DNO
  FROM EMP E, SAL S
 WHERE E.SALARY BETWEEN S.LOSAL AND S.HISAL
   AND S.GRADE = 1;

SELECT * FROM EMP_TEMP;

-- 실습 10-15
CREATE TABLE DEPT_TEMP2
    AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP2;
COMMIT;

-- 실습 10-16
UPDATE DEPT_TEMP2
   SET LOC = 'SEOUL';

SELECT * FROM DEPT_TEMP2;

-- 실습 10-17
ROLLBACK;

-- 실습 10-18
UPDATE DEPT_TEMP2
   SET DNAME = 'DATABASE',
       LOC = 'SEOUL'
 WHERE DNO = 40
;
ROLLBACK;
SELECT * FROM DEPT_TEMP2;

-- 실습 10-19
UPDATE DEPT_TEMP2
   SET (DNAME, LOC) = (SELECT DNAME, LOC
                         FROM DEPT
                        WHERE DNO = 30)
 WHERE DNO = 40;

SELECT * FROM DEPT_TEMP2;
COMMIT;

-- 실습 10-20
UPDATE DEPT_TEMP2
   SET DNAME = (SELECT DNAME
                  FROM DEPT
                 WHERE DNO = 40),
       LOC = (SELECT LOC
                FROM DEPT
               WHERE DNO = 40)
 WHERE DNO = 40;
 COMMIT;
 
SELECT *
  FROM DEPT_TEMP2
 WHERE DNO = 40  ;
-- 실습 10-21
UPDATE DEPT_TEMP2
   SET LOC = 'SEOUL'
 WHERE DNO = (SELECT DNO
                   FROM DEPT_TEMP2
                  WHERE DNAME='OPERATIONS');

SELECT * FROM DEPT_TEMP2;
UPDATE DEPT_TEMP2
   SET dname = 'PRODUCT'
WHERE dno = 40;

-- 실습 10-22
DROP TABLE EMP_TEMP2;
CREATE TABLE EMP_TEMP2
    AS SELECT * FROM EMP;

SELECT * FROM EMP_TEMP2;

-- 실습 10-23
DELETE FROM EMP_TEMP2
 WHERE JOB = 'MANAGER';

SELECT * FROM EMP_TEMP2;

-- 실습 10-24
DELETE FROM EMP_TEMP2
 WHERE ENO IN (SELECT E.ENO
                   FROM EMP_TEMP2 E, SAL S
                  WHERE E.SALARY BETWEEN S.LOSAL AND S.HISAL
                    AND S.GRADE = 3
                    AND DNO = 30);

SELECT * FROM EMP_TEMP2;

-- 실습 10-25
DELETE FROM EMP_TEMP2;

SELECT * FROM EMP_TEMP2;

