-- 실습 12-1
DROP TABLE EMP_DDL;

CREATE TABLE EMP_DDL(
   ENO      NUMBER(4),
   ENAME      VARCHAR2(10),
   JOB        VARCHAR2(9),
   MANAGER        NUMBER(4),
   HIREDATE   DATE,
   SALARY        NUMBER(7,2),
   COMMISSION       NUMBER(7,2),
   DNO     NUMBER(2)
);

DESC EMP_DDL;

SELECT *
FROM   EMP_DDL;

-- 실습 12-2
DROP TABLE DEPT_DDL;

CREATE TABLE DEPT_DDL
    AS SELECT * FROM DEPT;

DESC DEPT_DDL;

SELECT *
FROM   DEPT_DDL;

-- 실습 12-3
SELECT * FROM DEPT_DDL;

-- 실습 12-4
DROP TABLE EMP_DDL_30;

CREATE TABLE EMP_DDL_30
    AS SELECT *
         FROM EMP
        WHERE DNO = 30;

SELECT * FROM EMP_DDL_30;

-- 실습 12-5
DROP TABLE EMPDEPT_DDL;
CREATE TABLE EMPDEPT_DDL
    AS SELECT E.ENO, E.ENAME, E.JOB, E.MANAGER, E.HIREDATE,
              E.SALARY, E.COMMISSION, D.DNO, D.DNAME, D.LOC
         FROM EMP E, DEPT D
        --WHERE 1 <> 1
;

SELECT * FROM EMPDEPT_DDL;

-- 실습 12-6
DROP TABLE  EMP_ALTER;
CREATE TABLE EMP_ALTER
    AS SELECT * FROM EMP;

SELECT * FROM EMP_ALTER;

-- 실습 12-7
ALTER TABLE EMP_ALTER
  ADD HP VARCHAR2(20);

SELECT * FROM EMP_ALTER;

-- 실습 12-8
ALTER TABLE EMP_ALTER
RENAME COLUMN HP TO TEL;

SELECT * FROM EMP_ALTER;

-- 실습 12-9
ALTER TABLE EMP_ALTER
MODIFY ENO NUMBER(5);

DESC EMP_ALTER;

-- 실습 12-10
ALTER TABLE EMP_ALTER
 DROP COLUMN TEL;

SELECT * FROM EMP_ALTER;

-- 실습 12-11
RENAME EMP_ALTER TO EMP_RENAME;

-- 실습 12-12
DESC EMP_ALTER;

-- 실습 12-13
SELECT *
  FROM EMP_RENAME;

-- 실습 12-14
TRUNCATE TABLE EMP_RENAME;

SELECT *
  FROM EMP_RENAME;

-- 실습 12-15
DROP TABLE EMP_RENAME;

SELECT *
  FROM EMP_RENAME;
  
-- 실습 12-16
DESC EMP_RENAME;
