-- 잊기 전에 한 번 더 정답

-- 4-2
SELECT  JOB
  FROM EMP;
  
SELECT DISTINCT JOB
  FROM EMP;

-- 4-3
SELECT ENO AS 사번,
       ENAME AS EMPLOYEE_NAME,
       JOB,
       MANAGER AS MANAGER,
       HIREDATE,
       SALARY AS SALARYARY,
       COMMISSION AS COMMISSIONISSION,
       DNO AS DEPARTMENT_NO
  FROM EMP
ORDER BY DNO DESC, ENAME;
