-- 잊기 전에 한 번 더 정답
show user;
-- 5-1
SELECT *
  FROM EMP
 WHERE ENAME LIKE 'S%';

-- 5-2
SELECT EMPNO, ENAME, JOB, SAL, DNO
  FROM EMP 
 WHERE DNO = 30
    OR JOB = 'SALESMAN';

-- 5-3
-- 집합연산자를 사용하지 않은 방식
ALTER TABLE EMP RENAME COLUMN DNO TO DEPTNO;
SELECT * FROM EMP;
COMMIT;

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO IN (20, 30)
   AND SAL > 2000
 ORDER BY DEPTNO ASC;

-- 집합연산자를 사용한 방식
--A 집합
SELECT * 
  FROM EMP
 WHERE DEPTNO = 20 --5건
MINUS--UNION(13건) --UNION ALL(16건)
--B 집합
SELECT *
  FROM EMP
 WHERE SAL < 3000;--11건

-- 5-4
SELECT * 
  FROM EMP
 WHERE SAL < 2000
    OR SAL > 3000;

-- 5-5
SELECT ENAME, EMPNO, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 30
   AND ENAME LIKE '%E%'
   AND SAL NOT BETWEEN 1000 AND 2000;

-- 5-6
SELECT *
  FROM EMP
 WHERE COMM IS NULL
   AND MGR IS NOT NULL
   AND JOB IN ('MANAGER', 'CLERK')
   AND ENAME NOT LIKE '_L%';
